import { randomBytes } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { assertProjectState, type ProjectState } from "../domain/state.js";

export const STATE_PATH = ".draftforge/state.json";
export const SESSION_PATH = "SESSION.md";

export async function readProjectState(root: string): Promise<ProjectState> {
  const raw = await readFile(resolve(root, STATE_PATH), "utf8");
  const value: unknown = JSON.parse(raw);
  assertProjectState(value);
  return value;
}

export function serializeProjectState(state: ProjectState): string {
  return `${JSON.stringify(state, null, 2)}\n`;
}

export async function writeProjectState(root: string, state: ProjectState): Promise<void> {
  assertProjectState(state);
  await writeFileAtomic(resolve(root, STATE_PATH), serializeProjectState(state));
}

/**
 * Writes through a sibling temporary file so an interrupted run never leaves a
 * half-written state or handoff file behind.
 */
export async function writeFileAtomic(path: string, contents: string): Promise<void> {
  const directory = dirname(path);
  await mkdir(directory, { recursive: true });

  const temporaryPath = `${path}.${randomBytes(6).toString("hex")}.tmp`;
  await writeFile(temporaryPath, contents, "utf8");
  await rename(temporaryPath, path);
}

export function renderSession(state: ProjectState): string {
  const currentTask = state.workflow.currentTask ?? "None";
  const nextTask = state.workflow.nextTask ?? "None";
  const completedTasks = state.tasks.filter((task) => task.status === "done");
  const date = state.handoff.updatedAt.slice(0, 10);

  return `# Session handoff — ${date}

> Generated from \`.draftforge/state.json\`. Do not edit this file directly.

## What was done

- ${state.handoff.summary || "No summary recorded."}
- Current position: ${state.workflow.phaseId} — ${state.workflow.phaseName}; stage ${state.workflow.stage}; status ${state.workflow.status}.
- Current task: ${currentTask}. Next task: ${nextTask}.
- Completed: ${completedTasks.length === 0 ? "None" : completedTasks.map((task) => task.id).join(", ")}.

## Decisions locked

${renderList(state.handoff.decisionsLocked, "- None")}

## Open questions

${renderNumberedList(state.handoff.openQuestions, "None")}

## Next steps

${renderNumberedList(state.handoff.nextActions, "None")}

## Gotchas

${renderList([...state.handoff.blockers, ...state.handoff.gotchas], "- None")}

Last updated: ${state.handoff.updatedAt} by ${state.handoff.updatedBy}
`;
}

export async function writeSession(root: string, state: ProjectState): Promise<void> {
  await writeFileAtomic(resolve(root, SESSION_PATH), renderSession(state));
}

function renderList(items: readonly string[], emptyText: string): string {
  return items.length === 0 ? emptyText : items.map((item) => `- ${item}`).join("\n");
}

function renderNumberedList(items: readonly string[], emptyText: string): string {
  return items.length === 0 ? emptyText : items.map((item, index) => `${index + 1}. ${item}`).join("\n");
}
