import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = process.cwd();
const statePath = resolve(root, ".draftforge/state.json");
const sessionPath = resolve(root, "SESSION.md");
const state = JSON.parse(await readFile(statePath, "utf8"));

const list = (items, empty = "None") =>
  items.length === 0 ? empty : items.map((item) => `- ${item}`).join("\n");

const numbered = (items, empty = "None") =>
  items.length === 0 ? empty : items.map((item, index) => `${index + 1}. ${item}`).join("\n");

const completed = state.tasks.filter((task) => task.status === "done").map((task) => task.id);
const date = state.handoff.updatedAt.slice(0, 10);

const content = `# Session handoff — ${date}

> Generated from \`.draftforge/state.json\`. Do not edit this file directly.

## What was done

- ${state.handoff.summary || "No summary recorded."}
- Current position: ${state.workflow.phaseId} — ${state.workflow.phaseName}; stage ${state.workflow.stage}; status ${state.workflow.status}.
- Current task: ${state.workflow.currentTask ?? "None"}. Next task: ${state.workflow.nextTask ?? "None"}.
- Completed: ${completed.length === 0 ? "None" : completed.join(", ")}.

## Decisions locked

${list(state.handoff.decisionsLocked, "- None")}

## Open questions

${numbered(state.handoff.openQuestions)}

## Next steps

${numbered(state.handoff.nextActions)}

## Gotchas

${list([...state.handoff.blockers, ...state.handoff.gotchas], "- None")}

Last updated: ${state.handoff.updatedAt} by ${state.handoff.updatedBy}
`;

await writeFile(sessionPath, content, "utf8");
console.log("SESSION.md rendered from .draftforge/state.json");
